### ISSUE TITLE
Switch to react-scripts?

### ISSUE THREAD

**Issue by akx** [kcsry/infotv#20]
> onks jotain syytä olla käyttämättä ejectaamatonta react-scriptsiä 🤔

Totta kyllä tuokin

_Originally posted by @Hilzu in https://github.com/kcsry/infotv/pull/18#issuecomment-487543309_

**Comment by akx** [comment]
The `INFOTV_STYLE` system seemed nontrivial to port over to react-scripts.

**Comment by japsu** [comment]
`./switch-style.sh tracon`? symlinks etc.

**Comment by akx** [comment]
Will be superseded by #51.
